---
swagger: "2.0"
info:
  version: "2019-10-30T23:07:05Z"
  title: "twitter-api"
host: "hpbubuiaz6.execute-api.us-east-1.amazonaws.com"
basePath: "/prod"
schemes:
  - "https"
paths:
  /follow/{userHandle}/{followHandle}:
    get:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "followHandle"
          in: "path"
          required: true
          type: "string"
        - name: "userHandle"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/IsFollowingResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    post:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "followHandle"
          in: "path"
          required: true
          type: "string"
        - name: "userHandle"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
  /follow/{userHandle}/{followHandle}/unfollow:
    post:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "followHandle"
          in: "path"
          required: true
          type: "string"
        - name: "userHandle"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
  /statuses/post:
    post:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "PostStatusRequest"
          required: true
          schema:
            $ref: "#/definitions/PostStatusRequest"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /statuses/status/{statusId}:
    get:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "statusId"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/StatusResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
  /users/{handle}:
    get:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "handle"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/UserResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
  /users/{handle}/feed:
    get:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "handle"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/StatusesResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
  /users/{handle}/followers:
    get:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "handle"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/UsersResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
  /users/{handle}/following:
    get:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "handle"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/UsersResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
  /users/{handle}/profile:
    get:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "handle"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/ProfileResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    post:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "handle"
          in: "path"
          required: true
          type: "string"
        - in: "body"
          name: "UpdateProfileRequest"
          required: true
          schema:
            $ref: "#/definitions/UpdateProfileRequest"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /users/{handle}/signup:
    post:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "handle"
          in: "path"
          required: true
          type: "string"
        - in: "body"
          name: "SignupRequest"
          required: true
          schema:
            $ref: "#/definitions/SignupRequest"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /users/{handle}/story:
    get:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "handle"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/StatusesResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
definitions:
  Response:
    type: "object"
    properties:
      message:
        type: "string"
        description: "Operation status message"
    title: "Response"
  UserResponse:
    type: "object"
    properties:
      handle:
        type: "string"
        description: "The user handle"
      name:
        type: "string"
        description: "The user full name"
      password:
        type: "string"
        description: "The user password"
      profile:
        type: "string"
    title: "UserResponse"
  Empty:
    type: "object"
    title: "Empty Schema"
  IsFollowingResponse:
    type: "object"
    properties:
      isFollowing:
        type: "string"
        description: "Boolean of the follow in question"
    title: "IsFollowingResponse"
  StatusesResponse:
    title: "StatusesResponse"
    type: "array"
    items:
      type: "object"
      properties:
        message:
          type: "string"
        ownerHandle:
          type: "string"
        profile:
          type: "string"
        attachmentSrc:
          type: "string"
        date:
          type: "string"
        id:
          type: "string"
  UsersResponse:
    title: "UsersResponse"
    type: "array"
    items:
      type: "object"
      properties:
        handle:
          type: "string"
        name:
          type: "string"
        password:
          type: "string"
        profile:
          type: "string"
  SignupRequest:
    type: "object"
    properties:
      handle:
        type: "string"
        description: "The user handle"
      password:
        type: "string"
        description: "The user password"
      name:
        type: "string"
        description: "The user full name"
      profile:
        type: "string"
    title: "SignupRequest"
  StatusResponse:
    type: "object"
    properties:
      message:
        type: "string"
        description: "The status message"
      ownerHandle:
        type: "string"
        description: "The status ownerHandle"
      profile:
        type: "string"
        description: "The status ownerHandle"
      attachmentSrc:
        type: "string"
        description: "The status attachmentSrc"
      date:
        type: "string"
        description: "The status date"
      id:
        type: "string"
        description: "The status id"
    title: "StatusResponse"
  UpdateProfileRequest:
    type: "object"
    properties:
      handle:
        type: "string"
        description: "The profile user handle"
      src:
        type: "string"
        description: "The profile src"
    title: "UpdateProfileRequest"
  ProfileResponse:
    type: "object"
    properties:
      src:
        type: "string"
        description: "The profile src"
    title: "ProfileResponse"
  PostStatusRequest:
    type: "object"
    properties:
      message:
        type: "string"
        description: "The status message"
      attachmentSrc:
        type: "string"
        description: "The status attachmentSrc"
      ownerHandle:
        type: "string"
        description: "The status ownerHandle"
      profile:
        type: "string"
    title: "PostStatusRequest"
