---
swagger: "2.0"
info:
  version: "2019-10-21T21:52:33Z"
  title: "twitter-api"
host: "hpbubuiaz6.execute-api.us-east-1.amazonaws.com"
basePath: "/prod"
schemes:
- "https"
paths:
  /follow:
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /follow/{userHandle}:
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /follow/{userHandle}/{followHandle}:
    get:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "followHandle"
        in: "path"
        required: true
        type: "string"
      - name: "userHandle"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/IsFollowingResponse"
    post:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "followHandle"
        in: "path"
        required: true
        type: "string"
      - name: "userHandle"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Response"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /follow/{userHandle}/{followHandle}/unfollow:
    post:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "followHandle"
        in: "path"
        required: true
        type: "string"
      - name: "userHandle"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Response"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /statuses:
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /statuses/post:
    post:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "PostStatusRequest"
        required: true
        schema:
          $ref: "#/definitions/PostStatusRequest"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Response"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /statuses/{statusId}:
    get:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "statusId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/StatusResponse"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /users:
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /users/signup:
    post:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "SignupRequest"
        required: true
        schema:
          $ref: "#/definitions/SignupRequest"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Response"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /users/{handle}:
    get:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "handle"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/UserResponse"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /users/{handle}/feed:
    get:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "handle"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/FeedResponse"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /users/{handle}/followers:
    get:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "handle"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/FollowersResponse"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /users/{handle}/following:
    get:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "handle"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/FollowingResponse"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /users/{handle}/profile:
    get:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "handle"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/ProfileResponse"
    post:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "handle"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "UpdateProfileRequest"
        required: true
        schema:
          $ref: "#/definitions/UpdateProfileRequest"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Response"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /users/{handle}/story:
    get:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "handle"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/StoryResponse"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
definitions:
  FollowersResponse:
    type: "object"
    title: "FollowersResponse"
  IsFollowingResponse:
    type: "object"
    properties:
      isFollowing:
        type: "string"
        description: "Boolean of the follow in question"
    title: "IsFollowingResponse"
  FeedResponse:
    type: "object"
    title: "FeedResponse"
  SignupRequest:
    type: "object"
    properties:
      handle:
        type: "string"
        description: "The user handle"
      password:
        type: "string"
        description: "The user password"
      name:
        type: "string"
        description: "The user full name"
    title: "SignupRequest"
  StatusResponse:
    type: "object"
    properties:
      message:
        type: "string"
        description: "The status message"
      attachmentSrc:
        type: "string"
        description: "The status attachmentSrc"
      ownerHandle:
        type: "string"
        description: "The status ownerHandle"
      date:
        type: "string"
        description: "The status date"
      id:
        type: "string"
        description: "The status id"
    title: "StatusResponse"
  ProfileResponse:
    type: "object"
    properties:
      src:
        type: "string"
        description: "The profile src"
    title: "ProfileResponse"
  Response:
    type: "object"
    properties:
      message:
        type: "string"
        description: "Operation status message"
    title: "Response"
  UserResponse:
    type: "object"
    properties:
      handle:
        type: "string"
        description: "The user handle"
      name:
        type: "string"
        description: "The user full name"
      password:
        type: "string"
        description: "The user password"
    title: "UserResponse"
  Empty:
    type: "object"
    title: "Empty Schema"
  StoryResponse:
    type: "object"
    title: "StoryResponse"
  UpdateProfileRequest:
    type: "object"
    properties:
      handle:
        type: "string"
        description: "The profile user handle"
      src:
        type: "string"
        description: "The profile src"
    title: "UpdateProfileRequest"
  PostStatusRequest:
    type: "object"
    properties:
      message:
        type: "string"
        description: "The status message"
      attachmentSrc:
        type: "string"
        description: "The status attachmentSrc"
      ownerHandle:
        type: "string"
        description: "The status ownerHandle"
      date:
        type: "string"
        description: "The status date"
      id:
        type: "string"
        description: "The status id"
    title: "PostStatusRequest"
  FollowingResponse:
    type: "object"
    title: "FollowingResponse"
