---
swagger: "2.0"
info:
  version: "2019-11-22T05:35:12Z"
  title: "twitter-api"
host: "hpbubuiaz6.execute-api.us-east-1.amazonaws.com"
basePath: "/prod"
schemes:
  - "https"
paths:
  /follow/{userHandle}/{followHandle}:
    get:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "followHandle"
          in: "path"
          required: true
          type: "string"
        - name: "userHandle"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/IsFollowingResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    post:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "followHandle"
          in: "path"
          required: true
          type: "string"
        - name: "userHandle"
          in: "path"
          required: true
          type: "string"
        - in: "body"
          name: "FollowRequest"
          required: true
          schema:
            $ref: "#/definitions/FollowRequest"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
  /follow/{userHandle}/{followHandle}/unfollow:
    post:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "followHandle"
          in: "path"
          required: true
          type: "string"
        - name: "userHandle"
          in: "path"
          required: true
          type: "string"
        - in: "body"
          name: "FollowRequest"
          required: true
          schema:
            $ref: "#/definitions/FollowRequest"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
  /statuses/hashtag/{hashtag}:
    get:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "lastHashtag"
          in: "query"
          required: false
          type: "string"
        - name: "pageSize"
          in: "query"
          required: true
          type: "string"
        - name: "lastTimestamp"
          in: "query"
          required: false
          type: "string"
        - name: "hashtag"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/HashtagStatusesResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
  /statuses/post:
    post:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "PostStatusRequest"
          required: true
          schema:
            $ref: "#/definitions/PostStatusRequest"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /statuses/status/{statusId}:
    get:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "statusId"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/StatusResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
  /users/{handle}:
    get:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "handle"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/UserResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
  /users/{handle}/feed:
    get:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "lastHandle"
          in: "query"
          required: false
          type: "string"
        - name: "pageSize"
          in: "query"
          required: true
          type: "string"
        - name: "lastTimestamp"
          in: "query"
          required: false
          type: "string"
        - name: "handle"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/FeedStatusesResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
  /users/{handle}/followers:
    get:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "userHandle"
          in: "query"
          required: false
          type: "string"
        - name: "pageSize"
          in: "query"
          required: true
          type: "string"
        - name: "followHandle"
          in: "query"
          required: false
          type: "string"
        - name: "handle"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/UsersResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
  /users/{handle}/following:
    get:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "userHandle"
          in: "query"
          required: false
          type: "string"
        - name: "pageSize"
          in: "query"
          required: true
          type: "string"
        - name: "followHandle"
          in: "query"
          required: false
          type: "string"
        - name: "handle"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/UsersResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
  /users/{handle}/login:
    post:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "handle"
          in: "path"
          required: true
          type: "string"
        - in: "body"
          name: "LoginRequest"
          required: true
          schema:
            $ref: "#/definitions/LoginRequest"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/AuthResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /users/{handle}/logout:
    post:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "handle"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /users/{handle}/profile:
    post:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "handle"
          in: "path"
          required: true
          type: "string"
        - in: "body"
          name: "UpdateProfileRequest"
          required: true
          schema:
            $ref: "#/definitions/UpdateProfileRequest"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /users/{handle}/signup:
    post:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "handle"
          in: "path"
          required: true
          type: "string"
        - in: "body"
          name: "SignupRequest"
          required: true
          schema:
            $ref: "#/definitions/SignupRequest"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/AuthResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /users/{handle}/story:
    get:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "pageSize"
          in: "query"
          required: true
          type: "string"
        - name: "ownerHandle"
          in: "query"
          required: false
          type: "string"
        - name: "id"
          in: "query"
          required: false
          type: "string"
        - name: "handle"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/StoryStatusesResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
definitions:
  IsFollowingResponse:
    type: "object"
    properties:
      isFollowing:
        type: "string"
        description: "Boolean of the follow in question"
    title: "IsFollowingResponse"
  UsersResponse:
    type: "object"
    properties:
      users:
        type: "array"
        items:
          type: "object"
          properties:
            handle:
              type: "string"
            name:
              type: "string"
            password:
              type: "string"
      userHandle:
        type: "string"
      followHandle:
        type: "string"
    title: "UsersResponse"
  FeedStatusesResponse:
    type: "object"
    properties:
      statuses:
        type: "array"
        items:
          type: "object"
          properties:
            message:
              type: "string"
            ownerHandle:
              type: "string"
            attachmentSrc:
              type: "string"
            date:
              type: "string"
            id:
              type: "string"
            timestamp:
              type: "string"
      lastHandle:
        type: "string"
      lastTimestamp:
        type: "string"
    title: "FeedStatusesResponse"
  LoginRequest:
    type: "object"
    properties:
      handle:
        type: "string"
        description: "The user handle"
      password:
        type: "string"
    title: "UserRequest"
  SignupRequest:
    type: "object"
    properties:
      handle:
        type: "string"
        description: "The user handle"
      password:
        type: "string"
        description: "The user password"
      name:
        type: "string"
        description: "The user full name"
    title: "SignupRequest"
  StatusResponse:
    type: "object"
    properties:
      message:
        type: "string"
        description: "The status message"
      ownerHandle:
        type: "string"
        description: "The status ownerHandle"
      attachmentSrc:
        type: "string"
        description: "The status attachmentSrc"
      date:
        type: "string"
        description: "The status date"
      id:
        type: "string"
        description: "The status id"
      timestamp:
        type: "number"
    title: "StatusResponse"
  AuthResponse:
    type: "object"
    properties:
      message:
        type: "string"
        description: "The status message"
      authToken:
        type: "string"
    title: "AuthResponse"
  FollowRequest:
    type: "object"
    properties:
      userHandle:
        type: "string"
        description: "The user that is following"
      followHandle:
        type: "string"
        description: "The user to be followed"
      authorization:
        type: "string"
    title: "FollowRequest"
  Response:
    type: "object"
    properties:
      message:
        type: "string"
        description: "Operation status message"
    title: "Response"
  UserResponse:
    type: "object"
    properties:
      handle:
        type: "string"
        description: "The user handle"
      name:
        type: "string"
        description: "The user full name"
      password:
        type: "string"
        description: "The user password"
    title: "UserResponse"
  HashtagStatusesResponse:
    type: "object"
    properties:
      statuses:
        type: "array"
        items:
          type: "object"
          properties:
            message:
              type: "string"
            ownerHandle:
              type: "string"
            attachmentSrc:
              type: "string"
            date:
              type: "string"
            id:
              type: "string"
            timestamp:
              type: "number"
      lastHashtag:
        type: "string"
      lastTimestamp:
        type: "string"
    title: "HashtagStatusesResponse"
  Empty:
    type: "object"
    title: "Empty Schema"
  StoryStatusesResponse:
    type: "object"
    properties:
      statuses:
        type: "array"
        items:
          type: "object"
          properties:
            message:
              type: "string"
            ownerHandle:
              type: "string"
            attachmentSrc:
              type: "string"
            date:
              type: "string"
            id:
              type: "string"
            timestamp:
              type: "number"
      ownerHandle:
        type: "string"
      id:
        type: "string"
    title: "StoryStatusesResponse"
  UpdateProfileRequest:
    type: "object"
    properties:
      handle:
        type: "string"
        description: "The profile user handle"
      src:
        type: "string"
        description: "The profile src"
      authorization:
        type: "string"
    title: "UpdateProfileRequest"
  PostStatusRequest:
    type: "object"
    properties:
      message:
        type: "string"
        description: "The status message"
      attachmentSrc:
        type: "string"
        description: "The status attachmentSrc"
      ownerHandle:
        type: "string"
        description: "The status ownerHandle"
      authorization:
        type: "string"
    title: "PostStatusRequest"
