/**
 * twitter-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-11-19T00:53:19Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StatusesIndexResponseStatuses } from './statusesIndexResponseStatuses';


export interface StatusesIndexResponse { 
    statuses?: Array<StatusesIndexResponseStatuses>;
    startIndex?: string;
}
