/**
 * twitter-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-10-30T23:07:05Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface StatusesResponseInner { 
    message?: string;
    ownerHandle?: string;
    profile?: string;
    attachmentSrc?: string;
    date?: string;
    id?: string;
}
