/**
 * twitter-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-11-19T21:03:11Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UsersResponseUsers } from './usersResponseUsers';


export interface UsersResponse { 
    users?: Array<UsersResponseUsers>;
    userHandle?: string;
    followHandle?: string;
}
